DNA = DNA_string = 'ATGGTCTACATAGCTGACAAACAGCACGTAGCAATCGGTCGAATCTCGAGAGGCATATGGTCACATGATCGGTCGAGCGTGTTTCAAAGTTTGCGCCTAG'
introns = ['ATCGGTCGAA', 'ATCGGTCGAGCGTGT']

for intron in introns:
    DNA_string = DNA_string.replace(intron, "")
print(DNA)
print(DNA_string)
